# Generated by Django 5.2.7 on 2025-12-31 21:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('purchase', 'Purchase'), ('partial_refund', 'Partial Refund'), ('external_refund', 'External Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('buyer', 'Buyers Only'), ('vendor', 'Vendors Only'), ('admin', 'Admins Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
