# Generated by Django 4.2.7 on 2025-09-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_message_options_remove_message_parent_message_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Fix conversations.product_id from UUID to bigint to match vendor_products.id
            sql="""
                -- First, drop the foreign key constraint
                ALTER TABLE conversations DROP CONSTRAINT IF EXISTS conversations_product_id_fkey;
                
                -- Change the column type from UUID to bigint
                ALTER TABLE conversations ALTER COLUMN product_id TYPE bigint USING product_id::text::bigint;
                
                -- Add the foreign key constraint back
                ALTER TABLE conversations ADD CONSTRAINT conversations_product_id_fkey 
                FOREIGN KEY (product_id) REFERENCES vendor_products(id);
            """,
            reverse_sql="""
                -- Reverse: change back to UUID
                ALTER TABLE conversations DROP CONSTRAINT IF EXISTS conversations_product_id_fkey;
                ALTER TABLE conversations ALTER COLUMN product_id TYPE uuid USING product_id::text::uuid;
                ALTER TABLE conversations ADD CONSTRAINT conversations_product_id_fkey 
                FOREIGN KEY (product_id) REFERENCES products(id);
            """
        ),
    ]
