# Generated by Django 5.2.7 on 2026-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order Update'), ('payment', 'Payment'), ('message', 'Message'), ('system', 'System'), ('listing_approval', 'Listing Approval'), ('listing_rejection', 'Listing Rejection'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_response', 'Ticket Response'), ('security', 'Security Alert')], max_length=20),
        ),
    ]
