# Generated by Django 5.2.7 on 2026-02-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
