# Generated by Django 5.2.7 on 2026-02-24 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_message_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=100)),
                ('restriction_type', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'ip_restrictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
