# Generated by Django 5.2.7 on 2026-02-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_iprestriction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('listing_created', 'Listing Created'), ('listing_updated', 'Listing Updated'), ('listing_deleted', 'Listing Deleted'), ('listing_viewed', 'Listing Viewed'), ('search', 'Search'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('order_completed', 'Order Completed'), ('wishlist_added', 'Wishlist Added'), ('wishlist_removed', 'Wishlist Removed'), ('settings_changed', 'Settings Changed'), ('transaction_viewed', 'Transaction History Viewed'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('review_created', 'Review Created'), ('review_updated', 'Review Updated'), ('notification_viewed', 'Notification Viewed'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('user_block', 'User Blocked'), ('user_unblock', 'User Unblocked'), ('user_report', 'User Reported'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_rejected', 'Refund Rejected'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('wallet_credited', 'Wallet Credited'), ('wallet_withdrawn', 'Wallet Withdrawn'), ('vendor_refund_processed', 'Vendor Refund Processed'), ('login_failed', 'Failed Login Attempt'), ('security_alert', 'Security Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
