# Generated by Django 4.2.30 on 2026-04-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0008_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='shared.message'),
        ),
        migrations.CreateModel(
            name='GlobalBlast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_crypto', models.DecimalField(decimal_places=8, max_digits=20)),
                ('crypto_currency', models.CharField(max_length=10)),
                ('reach_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('products', models.ManyToManyField(related_name='global_blasts', to='shared.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_blasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'global_blasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
