# Generated by Django 5.2.7 on 2025-11-30 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('crypto_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('XMR', 'Monero')], max_length=10)),
                ('payment_address', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'PENDING'), ('partial', 'PARTIAL'), ('paid', 'PAID'), ('overpaid', 'OVERPAID'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], default='pending', max_length=20)),
                ('order_status', models.CharField(choices=[('pending_payment', 'PENDING_PAYMENT'), ('payment_received', 'PAYMENT_RECEIVED'), ('processing', 'PROCESSING'), ('paid', 'PAID'), ('delivered', 'DELIVERED'), ('confirmed', 'CONFIRMED'), ('disputed', 'DISPUTED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='pending_payment', max_length=20)),
                ('use_escrow', models.BooleanField(default=False)),
                ('escrow_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('dispute_opened', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(blank=True)),
                ('payment_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_opened_at', models.DateTimeField(blank=True, null=True)),
                ('product_credentials', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('buyer_wins', 'Buyer Wins - Full Refund'), ('vendor_wins', 'Vendor Wins - No Refund'), ('partial_refund', 'Partial Refund')], max_length=20)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_refund_disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_disputes', to='orders.order')),
            ],
            options={
                'db_table': 'marketplace_order_disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
