# Generated by Django 5.2.7 on 2025-11-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdispute',
            name='refund_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='payments.refundrequest'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_refund_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['status'], name='marketplace_status_201560_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['order'], name='marketplace_order_i_715ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['initiator'], name='marketplace_initiat_be8702_idx'),
        ),
    ]
