# Generated by Django 4.2.7 on 2025-09-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_escrow_fee_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending_payment', 'PENDING_PAYMENT'), ('payment_received', 'PAYMENT_RECEIVED'), ('processing', 'PROCESSING'), ('paid', 'PAID'), ('delivered', 'DELIVERED'), ('confirmed', 'CONFIRMED'), ('disputed', 'DISPUTED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='pending_payment', max_length=20),
        ),
    ]
