# Generated by Django 5.2.7 on 2026-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_is_giveaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_address',
            field=models.CharField(blank=True, help_text="Buyer's address for refunds in case of incorrect payment", max_length=255),
        ),
    ]
