# Generated by Django 5.2.7 on 2026-02-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_refund_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('partial', 'PARTIAL'), ('paid', 'PAID'), ('overpaid', 'OVERPAID'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='pending', max_length=20),
        ),
    ]
