# Generated by Django 5.2.7 on 2026-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('pending_payment', 'PENDING_PAYMENT'), ('payment_received', 'PAYMENT_RECEIVED'), ('processing', 'PROCESSING'), ('paid', 'PAID'), ('delivered', 'DELIVERED'), ('confirmed', 'CONFIRMED'), ('disputed', 'DISPUTED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='pending_payment', max_length=20),
        ),
    ]
