# Generated by Django 5.2.7 on 2026-02-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_created_at_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('pending_payment', 'PENDING_PAYMENT'), ('payment_received', 'PAYMENT_RECEIVED'), ('processing', 'PROCESSING'), ('paid', 'PAID'), ('delivered', 'DELIVERED'), ('confirmed', 'CONFIRMED'), ('disputed', 'DISPUTED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], db_index=True, default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('partial', 'PARTIAL'), ('paid', 'PAID'), ('overpaid', 'OVERPAID'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], db_index=True, default='pending', max_length=20),
        ),
    ]
