# Generated by Django 4.2.30 on 2026-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='was_highlighted_at_order',
            field=models.BooleanField(default=False, help_text='Was the product highlighted when this order was created?'),
        ),
    ]
