BEGIN;
--
-- Create model CryptoCurrency
--
CREATE TABLE "crypto_currencies" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_deleted" boolean NOT NULL, "name" varchar(100) NOT NULL, "symbol" varchar(10) NOT NULL UNIQUE, "logo_url" varchar(200) NULL, "current_price" numeric(20, 8) NOT NULL, "market_cap" numeric(20, 2) NOT NULL, "volume_24h" numeric(20, 2) NOT NULL, "price_change_24h" numeric(10, 2) NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model Category
--
CREATE TABLE "categories" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "name" varchar(100) NOT NULL, "description" text NOT NULL, "icon" varchar(50) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "is_featured" boolean NOT NULL, "parent_id" uuid NULL);
--
-- Create model Conversation
--
CREATE TABLE "conversations" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_deleted" boolean NOT NULL, "is_active" boolean NOT NULL, "product_id" bigint NULL);
CREATE TABLE "conversations_participants" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model Message
--
CREATE TABLE "messages" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "content" text NOT NULL, "is_read" boolean NOT NULL, "message_type" varchar(20) NOT NULL, "metadata" jsonb NOT NULL, "attachment" varchar(100) NULL, "conversation_id" uuid NOT NULL, "recipient_id" uuid NOT NULL, "sender_id" uuid NOT NULL);
--
-- Add field last_message to conversation
--
ALTER TABLE "conversations" ADD COLUMN "last_message_id" uuid NULL CONSTRAINT "conversations_last_message_id_77a159de_fk_messages_id" REFERENCES "messages"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "conversations_last_message_id_77a159de_fk_messages_id" IMMEDIATE;
--
-- Create model Notification
--
CREATE TABLE "notifications" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "type" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL, "data" jsonb NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model Order
--
CREATE TABLE "orders" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "status" varchar(20) NOT NULL, "total_amount" numeric(20, 8) NOT NULL, "shipping_address" jsonb NOT NULL, "tracking_number" varchar(100) NULL, "estimated_delivery" date NULL, "notes" text NOT NULL, "buyer_id" uuid NOT NULL, "crypto_currency_id" uuid NOT NULL, "vendor_id" uuid NOT NULL);
--
-- Create model Payment
--
CREATE TABLE "payments" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "amount" numeric(20, 8) NOT NULL, "payment_method" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "transaction_hash" varchar(255) NULL, "payment_date" timestamp with time zone NULL, "crypto_currency_id" uuid NOT NULL, "order_id" uuid NOT NULL);
--
-- Create model Product
--
CREATE TABLE "products" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "name" varchar(200) NOT NULL, "description" text NOT NULL, "price" numeric(20, 8) NOT NULL, "stock_quantity" integer NOT NULL CHECK ("stock_quantity" >= 0), "images" jsonb NOT NULL, "tags" jsonb NOT NULL, "is_featured" boolean NOT NULL, "is_approved" boolean NOT NULL, "rating" numeric(3, 2) NOT NULL, "review_count" integer NOT NULL CHECK ("review_count" >= 0), "slug" varchar(50) NOT NULL UNIQUE, "category_id" uuid NOT NULL, "crypto_currency_id" uuid NOT NULL, "vendor_id" uuid NOT NULL);
--
-- Create model OrderItem
--
CREATE TABLE "order_items" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "unit_price" numeric(20, 8) NOT NULL, "total_price" numeric(20, 8) NOT NULL, "order_id" uuid NOT NULL, "product_id" uuid NOT NULL);
--
-- Create model UserWallet
--
CREATE TABLE "user_wallets" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "balance_btc" numeric(20, 8) NOT NULL, "balance_xmr" numeric(20, 8) NOT NULL, "total_deposited_btc" numeric(20, 8) NOT NULL, "total_deposited_xmr" numeric(20, 8) NOT NULL, "total_withdrawn_btc" numeric(20, 8) NOT NULL, "total_withdrawn_xmr" numeric(20, 8) NOT NULL, "user_id" uuid NOT NULL UNIQUE);
--
-- Create model VendorApplication
--
CREATE TABLE "vendor_applications" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "business_name" varchar(200) NOT NULL, "business_description" text NOT NULL, "business_address" jsonb NOT NULL, "business_license" varchar(200) NOT NULL, "tax_id" varchar(100) NOT NULL, "bank_account" jsonb NOT NULL, "status" varchar(20) NOT NULL, "admin_notes" text NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model Review
--
CREATE TABLE "reviews" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "rating" integer NOT NULL CHECK ("rating" >= 0), "comment" text NOT NULL, "images" jsonb NOT NULL, "product_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model UserActivity
--
CREATE TABLE "user_activities" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "activity_type" varchar(50) NOT NULL, "description" text NOT NULL, "ip_address" inet NULL, "user_agent" text NOT NULL, "metadata" jsonb NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model UserReport
--
CREATE TABLE "user_reports" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "reason" varchar(50) NOT NULL, "description" text NOT NULL, "status" varchar(20) NOT NULL, "admin_notes" text NOT NULL, "conversation_id" uuid NULL, "message_id" uuid NULL, "reported_user_id" uuid NOT NULL, "reporter_id" uuid NOT NULL);
--
-- Create model WalletTransaction
--
CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "is_deleted" boolean NOT NULL, "transaction_type" varchar(20) NOT NULL, "amount" numeric(20, 8) NOT NULL, "crypto_currency" varchar(10) NOT NULL, "transaction_hash" varchar(255) NULL, "notes" text NOT NULL, "order_id" uuid NULL, "refund_request_id" uuid NULL, "wallet_id" uuid NOT NULL);
CREATE INDEX "crypto_currencies_symbol_59f95442_like" ON "crypto_currencies" ("symbol" varchar_pattern_ops);
ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_fc02df82_fk_categories_id" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "categories_slug_9bedfe6b_like" ON "categories" ("slug" varchar_pattern_ops);
CREATE INDEX "categories_parent_id_fc02df82" ON "categories" ("parent_id");
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_product_id_c2c693e3_fk_vendor_products_id" FOREIGN KEY ("product_id") REFERENCES "vendor_products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "conversations_product_id_c2c693e3" ON "conversations" ("product_id");
ALTER TABLE "conversations_participants" ADD CONSTRAINT "conversations_participan_conversation_id_user_id_7f9cba6f_uniq" UNIQUE ("conversation_id", "user_id");
ALTER TABLE "conversations_participants" ADD CONSTRAINT "conversations_partic_conversation_id_988acf55_fk_conversat" FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "conversations_participants" ADD CONSTRAINT "conversations_participants_user_id_968b244f_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "conversations_participants_conversation_id_988acf55" ON "conversations_participants" ("conversation_id");
CREATE INDEX "conversations_participants_user_id_968b244f" ON "conversations_participants" ("user_id");
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_5ef638db_fk_conversations_id" FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "messages" ADD CONSTRAINT "messages_recipient_id_6dcabc5c_fk_users_id" FOREIGN KEY ("recipient_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_dc5a0bbd_fk_users_id" FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "messages_conversation_id_5ef638db" ON "messages" ("conversation_id");
CREATE INDEX "messages_recipient_id_6dcabc5c" ON "messages" ("recipient_id");
CREATE INDEX "messages_sender_id_dc5a0bbd" ON "messages" ("sender_id");
CREATE INDEX "conversations_last_message_id_77a159de" ON "conversations" ("last_message_id");
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_468e288d_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "notifications_user_id_468e288d" ON "notifications" ("user_id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_buyer_id_3d1f9476_fk_users_id" FOREIGN KEY ("buyer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders" ADD CONSTRAINT "orders_crypto_currency_id_e32e6bf7_fk_crypto_currencies_id" FOREIGN KEY ("crypto_currency_id") REFERENCES "crypto_currencies" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders" ADD CONSTRAINT "orders_vendor_id_4ecc0960_fk_users_id" FOREIGN KEY ("vendor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_buyer_id_3d1f9476" ON "orders" ("buyer_id");
CREATE INDEX "orders_crypto_currency_id_e32e6bf7" ON "orders" ("crypto_currency_id");
CREATE INDEX "orders_vendor_id_4ecc0960" ON "orders" ("vendor_id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_crypto_currency_id_90515db8_fk_crypto_currencies_id" FOREIGN KEY ("crypto_currency_id") REFERENCES "crypto_currencies" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_6086ad70_fk_orders_id" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "payments_crypto_currency_id_90515db8" ON "payments" ("crypto_currency_id");
CREATE INDEX "payments_order_id_6086ad70" ON "payments" ("order_id");
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_a7a3a156_fk_categories_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "products" ADD CONSTRAINT "products_crypto_currency_id_7c486b42_fk_crypto_currencies_id" FOREIGN KEY ("crypto_currency_id") REFERENCES "crypto_currencies" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "products" ADD CONSTRAINT "products_vendor_id_7527517c_fk_users_id" FOREIGN KEY ("vendor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "products_slug_8f20884e_like" ON "products" ("slug" varchar_pattern_ops);
CREATE INDEX "products_category_id_a7a3a156" ON "products" ("category_id");
CREATE INDEX "products_crypto_currency_id_7c486b42" ON "products" ("crypto_currency_id");
CREATE INDEX "products_vendor_id_7527517c" ON "products" ("vendor_id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_412ad78b_fk_orders_id" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_dd557d5a_fk_products_id" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "order_items_order_id_412ad78b" ON "order_items" ("order_id");
CREATE INDEX "order_items_product_id_dd557d5a" ON "order_items" ("product_id");
ALTER TABLE "user_wallets" ADD CONSTRAINT "user_wallets_user_id_c089739c_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "vendor_applications" ADD CONSTRAINT "vendor_applications_user_id_ac1afe94_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "vendor_applications_user_id_ac1afe94" ON "vendor_applications" ("user_id");
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_id_user_id_a9c94d0e_uniq" UNIQUE ("product_id", "user_id");
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_id_d4b78cfe_fk_products_id" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_c23b0903_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reviews_product_id_d4b78cfe" ON "reviews" ("product_id");
CREATE INDEX "reviews_user_id_c23b0903" ON "reviews" ("user_id");
ALTER TABLE "user_activities" ADD CONSTRAINT "user_activities_user_id_ce552574_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_activities_user_id_ce552574" ON "user_activities" ("user_id");
CREATE INDEX "user_activi_user_id_290628_idx" ON "user_activities" ("user_id", "activity_type");
CREATE INDEX "user_activi_created_9fa3ca_idx" ON "user_activities" ("created_at");
ALTER TABLE "user_reports" ADD CONSTRAINT "user_reports_reporter_id_reported_use_43b26dd0_uniq" UNIQUE ("reporter_id", "reported_user_id", "conversation_id");
ALTER TABLE "user_reports" ADD CONSTRAINT "user_reports_reported_user_id_3544f147_fk_users_id" FOREIGN KEY ("reported_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_reports" ADD CONSTRAINT "user_reports_reporter_id_72332fa3_fk_users_id" FOREIGN KEY ("reporter_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_reports_reported_user_id_3544f147" ON "user_reports" ("reported_user_id");
CREATE INDEX "user_reports_reporter_id_72332fa3" ON "user_reports" ("reporter_id");
ALTER TABLE "wallet_transactions" ADD CONSTRAINT "wallet_transactions_order_id_2ac15662_fk_marketplace_orders_id" FOREIGN KEY ("order_id") REFERENCES "marketplace_orders" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wallet_transactions" ADD CONSTRAINT "wallet_transactions_refund_request_id_f23709f1_fk_refund_re" FOREIGN KEY ("refund_request_id") REFERENCES "refund_requests" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wallet_transactions" ADD CONSTRAINT "wallet_transactions_wallet_id_8cb3251a_fk_user_wallets_id" FOREIGN KEY ("wallet_id") REFERENCES "user_wallets" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wallet_transactions_order_id_2ac15662" ON "wallet_transactions" ("order_id");
CREATE INDEX "wallet_transactions_refund_request_id_f23709f1" ON "wallet_transactions" ("refund_request_id");
CREATE INDEX "wallet_transactions_wallet_id_8cb3251a" ON "wallet_transactions" ("wallet_id");
CREATE INDEX "wallet_tran_wallet__3d47ad_idx" ON "wallet_transactions" ("wallet_id", "created_at" DESC);
CREATE INDEX "wallet_tran_transac_377ecc_idx" ON "wallet_transactions" ("transaction_type");
COMMIT;
