# Generated by Django 5.2.7 on 2025-11-27 17:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_format', models.TextField(help_text='CSV format template')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bulk_upload_templates',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Sub-Categories',
                'db_table': 'product_subcategories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200)),
                ('listing_title', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('messengers', 'Messengers'), ('streaming', 'Streaming'), ('gaming', 'Gaming'), ('social', 'Social Media'), ('trading', 'Trading/Exchange'), ('software', 'Software'), ('other', 'Other')], max_length=50)),
                ('access_type', models.CharField(choices=[('full_ownership', 'Full Ownership'), ('access', 'Access'), ('shared', 'Shared')], max_length=50)),
                ('access_method', models.CharField(default='email_password', max_length=100)),
                ('account_balance', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('additional_info', models.TextField(blank=True)),
                ('delivery_time', models.CharField(choices=[('instant_auto', 'Instant Auto-delivery'), ('manual_24h', 'Manual delivery within 24hrs')], max_length=50)),
                ('delivery_method', models.CharField(default='instant', max_length=50)),
                ('special_features', models.JSONField(db_column='special_features', default=list)),
                ('region_restrictions', models.CharField(default='', max_length=200)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('account_age', models.CharField(blank=True, db_column='account_age', max_length=100, null=True)),
                ('main_images', models.JSONField(db_column='main_images', default=list)),
                ('gallery_images', models.JSONField(db_column='gallery_images', default=list)),
                ('documents', models.JSONField(db_column='documents', default=list)),
                ('tags', models.JSONField(db_column='tags', default=list)),
                ('auto_delivery_script', models.TextField(default='')),
                ('notes_for_buyer', models.TextField(default='')),
                ('credentials', models.TextField(blank=True)),
                ('credentials_visible', models.BooleanField(default=False)),
                ('escrow_enabled', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('verification_level', models.CharField(choices=[('unverified', 'Unverified'), ('basic', 'Basic Verification'), ('premium', 'Premium Verification'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_products', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
                ('sub_category', models.ForeignKey(blank=True, db_column='sub_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsubcategory')),
            ],
            options={
                'verbose_name_plural': 'Vendor Products',
                'db_table': 'vendor_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_views',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('vendor_reply', models.TextField(blank=True, null=True)),
                ('vendor_reply_date', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status'], name='vendor_prod_vendor__36c35d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['account_type', 'status'], name='vendor_prod_account_a1bcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='vendor_prod_price_2bfbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='vendor_prod_rating_7b609d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='vendor_prod_created_3fce10_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'user'], name='product_vie_product_36019e_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['viewed_at'], name='product_vie_viewed__28cb00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productview',
            unique_together={('product', 'user')},
        ),
    ]
