# Generated by Django 4.2.7 on 2025-09-02 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='access_method',
            field=models.CharField(default='email_password', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='account_age',
            field=models.CharField(blank=True, db_column='account_age', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_delivery_script',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_method',
            field=models.CharField(default='instant', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='documents',
            field=models.JSONField(db_column='documents', default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='main_images',
            field=models.JSONField(db_column='main_images', default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_for_buyer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='region_restrictions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='special_features',
            field=models.JSONField(db_column='special_features', default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_column='sub_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(db_column='tags', default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='verification_level',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('basic', 'Basic Verification'), ('premium', 'Premium Verification'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='approval_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(db_column='gallery_images', default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='product_subcategories',
        ),
    ]
