# Generated by Django 5.2.7 on 2025-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accepted_crypto',
            field=models.JSONField(db_column='accepted_crypto', default=list),
        ),
    ]
