# Generated by Django 5.2.7 on 2026-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_accepted_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('reserved', 'Reserved (Out of Stock)')], default='draft', max_length=20),
        ),
    ]
