# Generated by Django 5.2.7 on 2026-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_account_type_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_giveaway',
            field=models.BooleanField(default=False),
        ),
    ]
