# Generated by Django 4.2.7 on 2025-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='escrow_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
