# Generated by Django 4.2.30 on 2026-04-13 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_bulkuploadtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight_fee_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Promotional fee rate when highlighted (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='highlighted_until',
            field=models.DateTimeField(blank=True, help_text='Time until which the product remains highlighted', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Is this product currently highlighted as a special offer?'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='helpful_votes',
            field=models.ManyToManyField(blank=True, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
