# Generated by Django 4.2.7 on 2025-09-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_is_deleted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='headline',
            field=models.CharField(max_length=200, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=200, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='access_type',
            field=models.CharField(max_length=50, default='full_ownership'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_balance',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(max_length=50, default='instant_auto'),
        ),
        migrations.AddField(
            model_name='product',
            name='credentials',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='credentials_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
