# Generated by Django 4.2.7 on 2025-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_categories_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
