# Generated by Django 4.2.7 on 2025-09-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_fix_subcategories_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='access_type',
            field=models.CharField(choices=[('full_ownership', 'Full Ownership'), ('access', 'Access'), ('shared', 'Shared')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_balance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='credentials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(choices=[('instant_auto', 'Instant Auto-delivery'), ('manual_24h', 'Manual delivery within 24hrs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
