# Generated by Django 4.2.7 on 2025-09-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_access_type_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # This tells Django that the field is already BigAutoField in the database
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;",  # No-op reverse SQL
            state_operations=[
                migrations.AlterField(
                    model_name='product',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ]
        ),
    ]
