# Generated by Django 5.2.7 on 2026-01-07 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0005_add_vendor_fee_model'),
        ('products', '0003_alter_product_account_type_alter_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispute_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('product_not_received', 'Product Not Received'), ('product_defective', 'Product Defective'), ('product_not_as_described', 'Product Not As Described'), ('vendor_not_responsive', 'Vendor Not Responsive'), ('payment_issue', 'Payment Issue'), ('delivery_issue', 'Delivery Issue'), ('refund_issue', 'Refund Issue'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('refund_full', 'Full Refund to Buyer'), ('refund_partial', 'Partial Refund to Buyer'), ('refund_to_vendor', 'Payment to Vendor'), ('product_replacement', 'Product Replacement'), ('dispute_dismissed', 'Dispute Dismissed'), ('favor_buyer', 'Decision in Favor of Buyer'), ('favor_vendor', 'Decision in Favor of Vendor'), ('mutual_resolution', 'Mutual Resolution')], default='pending', max_length=50)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True, help_text='Detailed explanation of why this decision was made', null=True)),
                ('winning_party', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('vendor', 'Vendor'), ('neutral', 'Neutral/Shared Responsibility')], help_text='Which party the admin decided in favor of', max_length=20, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Refund amount in BTC', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_files', models.JSONField(blank=True, default=list, help_text='List of file URLs uploaded as evidence')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='products.product')),
                ('refund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_new', to='payments.refundrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal admin notes not visible to parties')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file URLs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='disputes.dispute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'priority'], name='disputes_di_status_3dbe35_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['buyer', 'status'], name='disputes_di_buyer_i_d53c02_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['vendor', 'status'], name='disputes_di_vendor__dfc8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['assigned_admin', 'status'], name='disputes_di_assigne_53b99f_idx'),
        ),
    ]
