# Generated by Django 5.2.7 on 2025-10-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='dispute_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
