# Generated by Django 5.2.7 on 2025-10-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_add_resolution_details'),
        ('disputes', '0002_alter_dispute_dispute_id'),
    ]

    operations = [
    ]
