# Generated by Django 5.2.7 on 2025-10-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_merge_20251008_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(choices=[('pending', 'Pending'), ('refund_full', 'Full Refund to Buyer'), ('refund_partial', 'Partial Refund to Buyer'), ('refund_to_vendor', 'Payment to Vendor'), ('product_replacement', 'Product Replacement'), ('dispute_dismissed', 'Dispute Dismissed'), ('favor_buyer', 'Decision in Favor of Buyer'), ('favor_vendor', 'Decision in Favor of Vendor'), ('mutual_resolution', 'Mutual Resolution')], default='pending', max_length=50),
        ),
    ]
