# Generated by Django 4.2.7 on 2025-08-24 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('vendor_username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('store_description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics & Tech', 'Electronics & Tech'), ('Digital Goods & Software', 'Digital Goods & Software'), ('Streaming Accounts', 'Streaming Accounts'), ('Gaming Accounts', 'Gaming Accounts'), ('Educational Services', 'Educational Services'), ('VPN & Security', 'VPN & Security'), ('Design & Creative', 'Design & Creative'), ('Business Tools', 'Business Tools'), ('Other', 'Other')], max_length=50)),
                ('btc_address', models.CharField(blank=True, max_length=100, null=True)),
                ('xmr_address', models.CharField(blank=True, max_length=100, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
