# Generated by Django 4.2.7 on 2025-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual/Sole Proprietor'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('llc', 'Limited Liability Company (LLC)'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='preferred_payment',
            field=models.CharField(blank=True, choices=[('btc', 'Bitcoin (BTC)'), ('xmr', 'Monero (XMR)'), ('both', 'Both BTC & XMR'), ('escrow', 'Escrow Only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='social_media',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='target_market',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='years_in_business',
            field=models.CharField(blank=True, choices=[('less-than-1', 'Less than 1 year'), ('1-2', '1-2 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('more-than-10', 'More than 10 years')], max_length=20, null=True),
        ),
    ]
