# Generated by Django 4.2.7 on 2025-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorapplication_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_applications/images/'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='vendor_applications/documents/'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_applications/logos/'),
        ),
    ]
