# Generated by Django 4.2.7 on 2025-08-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('wallet', 'Crypto Wallet'), ('buy', 'Buy with Card'), ('exchange', 'Exchange Transfer')], default='wallet', max_length=20)),
                ('btcpay_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('btcpay_checkout_link', models.URLField(blank=True, null=True)),
                ('payment_address', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('received_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('monero_subaddress_index', models.IntegerField(blank=True, null=True)),
                ('monero_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Fully Paid'), ('overpaid', 'Overpaid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=1)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency')),
            ],
            options={
                'db_table': 'payment_addresses',
            },
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('escrow_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('escrow_fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('disputed', 'Disputed'), ('released', 'Released to Vendor'), ('refunded', 'Refunded to Buyer'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('auto_release_enabled', models.BooleanField(default=True)),
                ('auto_release_days', models.IntegerField(default=7)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_escrows', to=settings.AUTH_USER_MODEL)),
                ('payment_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.paymentaddress')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_escrows', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_escrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escrow_payments',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('block_height', models.IntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_transaction', models.JSONField(blank=True, null=True)),
                ('payment_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentaddress')),
            ],
            options={
                'db_table': 'blockchain_transactions',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('webhook_type', models.CharField(choices=[('btcpay', 'BTCPay Server'), ('monero', 'Monero RPC'), ('manual', 'Manual Update')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_received', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.paymentaddress')),
            ],
            options={
                'db_table': 'payment_webhooks',
                'indexes': [models.Index(fields=['external_id'], name='payment_web_externa_1fb177_idx'), models.Index(fields=['processed'], name='payment_web_process_d3b66c_idx'), models.Index(fields=['webhook_type'], name='payment_web_webhook_708f61_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('escrow_enabled', models.BooleanField(default=True)),
                ('auto_accept_threshold', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('payment_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('escrow_fee_percentage', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
                'unique_together': {('vendor', 'crypto_currency')},
            },
        ),
        migrations.AddIndex(
            model_name='paymentaddress',
            index=models.Index(fields=['order_id'], name='payment_add_order_i_5e8ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaddress',
            index=models.Index(fields=['payment_address'], name='payment_add_payment_b18eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaddress',
            index=models.Index(fields=['status'], name='payment_add_status_a215b3_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayment',
            index=models.Index(fields=['status'], name='escrow_paym_status_b4b2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayment',
            index=models.Index(fields=['auto_release_at'], name='escrow_paym_auto_re_4e11db_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_9bd57a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['confirmed'], name='blockchain__confirm_5be7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['block_height'], name='blockchain__block_h_2b9cc6_idx'),
        ),
    ]
