# Generated by Django 5.2.7 on 2025-11-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '__first__'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='orders.order'),
        ),
    ]
