# Generated by Django 4.2.7 on 2025-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhook',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
