# Generated by Django 5.2.7 on 2025-11-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directpayment',
            name='crypto_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='directpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='directpayment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_escrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_escrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_escrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentaddress',
            name='crypto_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='payment_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.paymentaddress'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='payment_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentaddress'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='crypto_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='payment_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.paymentaddress'),
        ),
        migrations.AddField(
            model_name='payout',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='crypto_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='payout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='directpayment',
            index=models.Index(fields=['status'], name='direct_paym_status_6dab51_idx'),
        ),
        migrations.AddIndex(
            model_name='directpayment',
            index=models.Index(fields=['expires_at'], name='direct_paym_expires_a60abd_idx'),
        ),
        migrations.AddIndex(
            model_name='directpayment',
            index=models.Index(fields=['vendor_address'], name='direct_paym_vendor__d90697_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaddress',
            index=models.Index(fields=['order_id'], name='payment_add_order_i_5e8ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaddress',
            index=models.Index(fields=['payment_address'], name='payment_add_payment_b18eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaddress',
            index=models.Index(fields=['status'], name='payment_add_status_a215b3_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayment',
            index=models.Index(fields=['status'], name='escrow_paym_status_b4b2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowpayment',
            index=models.Index(fields=['auto_release_at'], name='escrow_paym_auto_re_4e11db_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_9bd57a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['confirmed'], name='blockchain__confirm_5be7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['block_height'], name='blockchain__block_h_2b9cc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('vendor', 'crypto_currency')},
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['external_id'], name='payment_web_externa_1fb177_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['processed'], name='payment_web_process_d3b66c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['webhook_type'], name='payment_web_webhook_708f61_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payouts_status_20cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['payout_type'], name='payouts_payout__88338d_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['auto_release_at'], name='payouts_auto_re_e61c20_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['vendor', 'status'], name='payouts_vendor__f8d117_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['vendor', '-created_at'], name='refund_requ_vendor__b1605c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['buyer', '-created_at'], name='refund_requ_buyer_i_ca301d_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status'], name='refund_requ_status_2691a2_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['order'], name='refund_requ_order_i_09d9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['vendor_refund_required', 'vendor_refund_completed'], name='refund_requ_vendor__151987_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['vendor_decision_deadline'], name='refund_requ_vendor__ee1efc_idx'),
        ),
    ]
