# Generated by Django 5.2.7 on 2025-10-12 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_status'),
        ('payments', '0002_paymentwebhook_delivery_id'),
        ('shared', '0003_auto_20250920_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('vendor_address', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_direct_payments', to=settings.AUTH_USER_MODEL)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payment', to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'direct_payments',
                'indexes': [models.Index(fields=['status'], name='direct_paym_status_6dab51_idx'), models.Index(fields=['expires_at'], name='direct_paym_expires_a60abd_idx'), models.Index(fields=['vendor_address'], name='direct_paym_vendor__d90697_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payout_type', models.CharField(choices=[('escrow', 'Escrow Release'), ('direct', 'Direct Payment')], max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('platform_fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('escrow_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('vendor_address', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('auto_release_enabled', models.BooleanField(default=True)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_payouts', to=settings.AUTH_USER_MODEL)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts',
                'indexes': [models.Index(fields=['status'], name='payouts_status_20cd29_idx'), models.Index(fields=['payout_type'], name='payouts_payout__88338d_idx'), models.Index(fields=['auto_release_at'], name='payouts_auto_re_e61c20_idx'), models.Index(fields=['vendor', 'status'], name='payouts_vendor__f8d117_idx')],
            },
        ),
    ]
