# Generated by Django 5.2.7 on 2025-11-30 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='buyer',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_decision_notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_decision_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('buyer_wins', 'Buyer Wins'), ('vendor_wins', 'Vendor Wins'), ('partial_refund', 'Partial Refund')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='admin_decision_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='admin_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='admin_decision_notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_refund_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_refund_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_refund_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_refund_transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
