# Generated by Django 5.2.7 on 2025-12-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_external_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='vendor_payment_source',
            field=models.CharField(blank=True, choices=[('platform', 'Platform Wallet'), ('external', 'External Wallet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_refund_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
