# Generated by Django 5.2.7 on 2025-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_directpayment_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpayment',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='directpayment',
            name='net_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='directpayment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
