# Generated by Django 5.2.7 on 2025-10-14 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_directpayment_escrow_fee_directpayment_net_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_fee_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform commission rate (%)', max_digits=5)),
                ('escrow_fee_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Escrow fee rate (%)', max_digits=5)),
                ('streaming_commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Streaming services commission rate (%)', max_digits=5)),
                ('software_commission_rate', models.DecimalField(decimal_places=2, default=4.0, help_text='Software & tools commission rate (%)', max_digits=5)),
                ('gaming_commission_rate', models.DecimalField(decimal_places=2, default=6.0, help_text='Gaming commission rate (%)', max_digits=5)),
                ('services_commission_rate', models.DecimalField(decimal_places=2, default=7.0, help_text='Digital services commission rate (%)', max_digits=5)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Default commission rate for new vendors (%)', max_digits=5)),
                ('min_commission_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Minimum allowed commission rate (%)', max_digits=5)),
                ('max_commission_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Maximum allowed commission rate (%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Settings',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
    ]
