# Generated by Django 5.2.7 on 2025-12-05 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refundrequest_vendor_external_wallet_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom commission rate (%) for this vendor. If null, uses default platform rate.', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vendor_fees', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_fee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Fee',
                'verbose_name_plural': 'Vendor Fees',
                'ordering': ['-updated_at'],
            },
        ),
    ]
