# Generated by Django 5.2.7 on 2026-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_vendor_fee_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpayment',
            name='amount_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='directpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_type',
            field=models.CharField(choices=[('escrow', 'Escrow Release'), ('direct', 'Direct Payment'), ('refund', 'Partial Payment Refund')], max_length=10),
        ),
    ]
