# Generated by Django 5.2.7 on 2026-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_directpayment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaddress',
            name='linked_order_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of order IDs covered by this payment in case of bulk purchase'),
        ),
    ]
