# Generated by Django 5.2.7 on 2026-02-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentaddress_linked_order_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowpayment',
            name='payment_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='payments.paymentaddress'),
        ),
    ]
