# Generated by Django 5.2.7 on 2026-02-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_status'),
        ('payments', '0009_alter_escrowpayment_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payment', to='orders.order'),
        ),
    ]
