# Generated by Django 5.2.7 on 2026-03-08 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_blockchaintransaction_created_at_and_more'),
        ('shared', '0008_alter_announcement_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaddress',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cryptocurrency')),
            ],
            options={
                'db_table': 'admin_withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_withd_admin_i_883dbd_idx')],
            },
        ),
    ]
