# Generated by Django 5.2.7 on 2026-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_paymentaddress_confirmed_at_adminwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_sweep_btc_address',
            field=models.CharField(blank=True, help_text='Personal BTC address for auto-sweep', max_length=255),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_sweep_enabled',
            field=models.BooleanField(default=False, help_text='Automatically forward platform profits to personal wallets'),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_sweep_min_buffer',
            field=models.DecimalField(decimal_places=8, default=0.0005, help_text='Minimum BTC buffer to keep in hot wallet for fees', max_digits=20),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_sweep_time',
            field=models.TimeField(default='17:00', help_text='Daily time to perform the sweep (Local time)'),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_sweep_whatsapp_number',
            field=models.CharField(default='+923188802535', help_text='WhatsApp number for notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_sweep_xmr_address',
            field=models.CharField(blank=True, help_text='Personal XMR address for auto-sweep', max_length=255),
        ),
    ]
