# Generated by Django 5.2.7 on 2026-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_commissionsettings_auto_sweep_btc_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsettings',
            name='auto_sweep_min_buffer',
            field=models.DecimalField(decimal_places=8, default=5e-05, help_text='Minimum BTC buffer to keep in hot wallet for fees', max_digits=20),
        ),
    ]
