# Generated by Django 4.2.7 on 2025-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_date_of_birth_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escrow_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
