# Generated by Django 5.2.7 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='btc_payout_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xmr_payout_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
