# Generated by Django 5.2.7 on 2025-12-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_btc_payout_address_user_xmr_payout_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='non_escrow_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
