# Generated by Django 5.2.7 on 2026-01-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_notify_login_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_phrase',
            field=models.CharField(blank=True, help_text='BIP39 Mnemonic phrase for account recovery', max_length=255, null=True),
        ),
    ]
